#!/usr/bin/env bash

# default to cloned Gist, but accept an argument instead
dest=/Volumes/Cloud/GitHub/Gists/bash_profile
if [ ! -z ${1+x} ]; then
	dest=$1
fi

# clone current profile information
cat "$HOME/.bash_profile" >"$dest/bash_profile"
cat "$HOME/.bashrc" >"$dest/bashrc"
cat "$HOME/.profile" >"$dest/profile"
crontab -l >"$dest/crontab"

cd $dest
git add -A
git commit -m "Automatic Backup"

ssh-agent bash -c 'ssh-add $GH_SSH_KEY; git push' 2>&1
