#!/usr/bin/env bash

usage() {
	echo "Usage: `basename $0` enable|disable"
	echo ""
	echo "Arguments are case-sensitive."
	echo ""
	exit 65
}

cloudSyncingEnable() {
	printf "Enabling cloud syncing...\n";
	printf "  Dropbox\n"
	open "$HOME/Applications/Dropbox.app" 2>&1
	printf "  Google Backup and Sync\n"
	open "$HOME/Applications/Backup and Sync.app" 2>&1
	printf "  OneDrive\n"
	open "/Applications/OneDrive.app" 2>&1
	printf "...ready.\n"
}
 
cloudSyncingDisable() {
	printf "Disabling cloud syncing...\n"
	printf "  Dropbox\n    "
	osascript -e 'quit app "Dropbox"' 2>&1
	while pgrep -xq -- "Dropbox"; do
		printf "."
		sleep 2
	done
	printf "\n  Google Backup and Sync\n    "
	killall -QUIT -m "Backup and Sync*" 2>&1
	while pgrep -xq -- "Backup and Sync*"; do
		printf "."
		sleep 2
	done
	printf "\n  OneDrive\n    "
	osascript -e 'quit app "OneDrive"' 2>&1
	while pgrep -xq -- "OneDrive"; do
		printf "."
		sleep 2
	done
	printf "\n...processor bandwidth returned to user.\n"
}

case "$1" in
"enable")
	cloudSyncingEnable
	;;
"disable")
	cloudSyncingDisable
	;;
*)
	usage
	;;
esac