#!/usr/bin/env bash

usage() {
	echo "Usage: `basename $0` enable|disable"
	echo ""
	echo "Arguments are case-sensitive."
	echo ""
	exit 65
}

cloudSyncingEnable() {
	printf "Enabling cloud syncing...\n";
	printf "  Dropbox\n"
	open -a "Dropbox" 2>&1
	printf "  Google Backup and Sync\n"
	open -a "Backup and Sync" 2>&1
	printf "  Microsoft OneDrive\n"
	open -a "OneDrive" 2>&1
	printf "Ready.\n"
}
 
cloudSyncingDisable() {
	printf "Disabling cloud syncing...\n"
	osascript -e 'quit app "Dropbox"' 2>&1
	killall -QUIT "Backup and Sync" 2>&1
	osascript -e 'quit app "OneDrive"' 2>&1
	printf "  Dropbox"
	while pgrep -xq -- "Dropbox"; do
		printf "."
		sleep 2
	done
	printf "\n  Google Backup and Sync"
	while pgrep -xq -- "Backup and Sync*"; do
		printf "."
		sleep 2
	done
	printf "\n  Microsoft OneDrive"
	while pgrep -xq -- "OneDrive"; do
		printf "."
		sleep 2
	done
	printf "\nProcessor bandwidth returned to user.\n"
}

case "$1" in
"enable")
	cloudSyncingEnable
	;;
"disable")
	cloudSyncingDisable
	;;
*)
	usage
	;;
esac