#!/usr/bin/env bash

itunesScripts="$HOME/Library/Scripts/Applications/iTunes"
podcastScripts="$itunesScripts/Metadata/Podcast Cleanup"

# switch to Music & Audiobooks library
audiobooks >/dev/null  2>&1

# exploit first-named-track-autoplay bug for joy
osascript "$itunesScripts/Rename Track for First Play.scpt"

# fix podcast metadata automagically
osascript "$podcastScripts/Convert Miscategorized to Audiobook.scpt"
osascript "$podcastScripts/TAL without Metadata.scpt"
for episodeUpdater in "$podcastScripts/Episode Updaters/"*.scpt
do
	osascript "$episodeUpdater"
done
osascript "$podcastScripts/TAL without Metadata.scpt"