#!/usr/bin/env bash

itunesScripts="$HOME/Library/Scripts/Applications/iTunes"
podcastScripts="$itunesScripts/Metadata/Podcast Cleanup"

exec 3>&1
exec 1> /dev/null

# switch to Music & Audiobooks library
# audiobooks
open -a "iTunes"

# exploit first-named-track-autoplay bug for joy
# osascript "$itunesScripts/Rename Track for First Play.scpt"

# fix podcast metadata automagically
osascript "$podcastScripts/Convert Miscategorized to Audiobook.scpt"
osascript "$podcastScripts/TAL without Metadata.scpt"
for episodeUpdater in "$podcastScripts/Episode Updaters/"*.scpt
do
	osascript "$episodeUpdater"
done
osascript "$podcastScripts/TAL without Metadata.scpt"

exec 1>&3
