#!/usr/bin/env bash
# prerequsites
# brew install mediainfo
# brew install homebrew/dupes/grep --with-default-names

# Usage:
# movieIndexer [path to index] [output file]
# default path is the current working directory
# default output is a file named Movies.md in the current working directory
# for custom output file, a custom path must be provided as well

# set up output file
if [ ! -z ${2+x} ]; then
	indexFile="$2"
else
	indexFile="$PWD/Movies.md"
fi

# set up path to index
if [ ! -z ${1+x} ]; then
	cd "$1"
fi

# logging output
echo "Writing index of movies in $PWD to $indexFile..."
echo > "$indexFile"

# count movies
count=0

# walk through every file and directory in the path
shopt -s extglob
for d in ./!(_*)/; do
	directory="$(basename "$d")"
	title=""
	if [ `ls -1 "$d" | wc -l` != "1" ] || [[ $directory == *[_]* ]]; then
		indent="  "
		if [ `ls -1 "$d" | wc -l` != "1" ]; then
			echo "  - $directory" >> "$indexFile"
			indent="$indent  "
		fi
		for f in "$d"*; do
			movie=""
			track=""
			if [[ $f != *"H.264"* ]]; then
				title=""
				filename="$(basename "$f" | grep -oP "((?<=\d{2,2}(-\d) )|(?<=\d{2,2} )).*(?=\.\w{3,3})")"
				if [[ $filename == *[_]* ]] || [[ $filename == [0-9][0-9]" "* ]]; then 
					movie="$(mediainfo "$f" | grep -oP "(?<=^Movie name                               : ).*")"
					if [ -z "$movie" ]; then
						track="$(mediainfo "$f" | grep -oP "(?<=^Track name                               : ).*")"
						if [ -z "$track" ]; then
							title="$filename"
						else
							title="$track"
						fi
					else
						title="$movie"
					fi
				fi
				if [[ -z $title ]]; then
					title="$filename"
				fi
				echo "$indent- $title" >> "$indexFile"
				((count++))
			fi
		done
	else
		echo "  - $directory" >> "$indexFile" 
		((count++))
	fi
done
shopt -u extglob

echo "Index updated ($count movies)"