#!/usr/bin/env bash
# prerequisites
# https://github.com/manolomartinez/greg
# pip3 install --user greg

gregDir=$HOME/Library/Application\ Support/greg/Podcasts
iTunesLibrary=$HOME/Music/iTunes\ \(Music\ \&\ Audiobooks\)
autoAddDir=$iTunesLibrary/iTunes\ Media/Automatically\ Add\ to\ iTunes.localized

greg sync 2>&1
if [ -n "$(ls "$gregDir")" ]; then
	printf "\033[1;32mMoving downloaded podcasts to iTunes"
	mv "$gregDir"/* "$autoAddDir"
else
	printf "\033[1;31mNo podcasts ready for download\033[0m\n"
fi
printf "\033[0m\n"