#!/usr/bin/env bash

# default to usual location, but accept an argument instead
scripts=$HOME/Library/Scripts
if [ ! -z ${1+x} ]; then
	scripts=$1
fi

# push any script changes to GitHub
cd $scripts
git add -A
git commit -m "Automatic Backup"
ssh-agent bash -c 'ssh-add "$GH_SSH_KEY"; git push' 2>&1

